"""add cascade delete to foreign keys

Revision ID: 2c374eb0fddb
Revises: e62a9e695479
Create Date: 2026-06-01 01:05:51.937830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c374eb0fddb'
down_revision: Union[str, Sequence[str], None] = 'e62a9e695479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'activities', ['id'])
    op.drop_constraint(op.f('activities_org_id_fkey'), 'activities', type_='foreignkey')
    op.drop_constraint(op.f('activities_user_id_fkey'), 'activities', type_='foreignkey')
    op.create_foreign_key(None, 'activities', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'activities', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'labels', ['id'])
    op.drop_constraint(op.f('labels_team_id_fkey'), 'labels', type_='foreignkey')
    op.drop_constraint(op.f('labels_org_id_fkey'), 'labels', type_='foreignkey')
    op.drop_constraint(op.f('labels_proj_id_fkey'), 'labels', type_='foreignkey')
    op.create_foreign_key(None, 'labels', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'labels', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'labels', 'projects', ['proj_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'milestones', ['id'])
    op.drop_constraint(op.f('milestones_org_id_fkey'), 'milestones', type_='foreignkey')
    op.drop_constraint(op.f('milestones_team_id_fkey'), 'milestones', type_='foreignkey')
    op.drop_constraint(op.f('milestones_proj_id_fkey'), 'milestones', type_='foreignkey')
    op.create_foreign_key(None, 'milestones', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'milestones', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'milestones', 'projects', ['proj_id'], ['id'], ondelete='CASCADE')
    op.alter_column('organizationmembers', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_unique_constraint(None, 'organizationmembers', ['id'])
    op.drop_constraint(op.f('organizationmembers_org_id_fkey'), 'organizationmembers', type_='foreignkey')
    op.drop_constraint(op.f('organizationmembers_user_id_fkey'), 'organizationmembers', type_='foreignkey')
    op.create_foreign_key(None, 'organizationmembers', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'organizationmembers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'organizations', ['id'])
    op.create_unique_constraint(None, 'projects', ['id'])
    op.drop_constraint(op.f('projects_team_id_fkey'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('projects_created_by_fkey'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('projects_org_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'projects', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'projects', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'tasklabels', ['id'])
    op.drop_constraint(op.f('tasklabels_label_id_fkey'), 'tasklabels', type_='foreignkey')
    op.drop_constraint(op.f('tasklabels_task_id_fkey'), 'tasklabels', type_='foreignkey')
    op.create_foreign_key(None, 'tasklabels', 'labels', ['label_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tasklabels', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'tasks', ['id'])
    op.drop_constraint(op.f('tasks_org_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_created_by_fkey'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_proj_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_team_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_assignee_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tasks', 'projects', ['proj_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tasks', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tasks', 'users', ['assignee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tasks', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.alter_column('teammembers', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_unique_constraint(None, 'teammembers', ['id'])
    op.drop_constraint(op.f('teammembers_user_id_fkey'), 'teammembers', type_='foreignkey')
    op.drop_constraint(op.f('teammembers_team_id_fkey'), 'teammembers', type_='foreignkey')
    op.create_foreign_key(None, 'teammembers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'teammembers', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'teams', ['id'])
    op.drop_constraint(op.f('teams_created_by_fkey'), 'teams', type_='foreignkey')
    op.drop_constraint(op.f('teams_org_id_fkey'), 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'teams', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_foreign_key(op.f('teams_org_id_fkey'), 'teams', 'organizations', ['org_id'], ['id'])
    op.create_foreign_key(op.f('teams_created_by_fkey'), 'teams', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'teams', type_='unique')
    op.drop_constraint(None, 'teammembers', type_='foreignkey')
    op.drop_constraint(None, 'teammembers', type_='foreignkey')
    op.create_foreign_key(op.f('teammembers_team_id_fkey'), 'teammembers', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(op.f('teammembers_user_id_fkey'), 'teammembers', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'teammembers', type_='unique')
    op.alter_column('teammembers', 'joined_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_assignee_id_fkey'), 'tasks', 'users', ['assignee_id'], ['id'])
    op.create_foreign_key(op.f('tasks_team_id_fkey'), 'tasks', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(op.f('tasks_proj_id_fkey'), 'tasks', 'projects', ['proj_id'], ['id'])
    op.create_foreign_key(op.f('tasks_created_by_fkey'), 'tasks', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('tasks_org_id_fkey'), 'tasks', 'organizations', ['org_id'], ['id'])
    op.drop_constraint(None, 'tasks', type_='unique')
    op.drop_constraint(None, 'tasklabels', type_='foreignkey')
    op.drop_constraint(None, 'tasklabels', type_='foreignkey')
    op.create_foreign_key(op.f('tasklabels_task_id_fkey'), 'tasklabels', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key(op.f('tasklabels_label_id_fkey'), 'tasklabels', 'labels', ['label_id'], ['id'])
    op.drop_constraint(None, 'tasklabels', type_='unique')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_org_id_fkey'), 'projects', 'organizations', ['org_id'], ['id'])
    op.create_foreign_key(op.f('projects_created_by_fkey'), 'projects', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('projects_team_id_fkey'), 'projects', 'teams', ['team_id'], ['id'])
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_constraint(None, 'organizationmembers', type_='foreignkey')
    op.drop_constraint(None, 'organizationmembers', type_='foreignkey')
    op.create_foreign_key(op.f('organizationmembers_user_id_fkey'), 'organizationmembers', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('organizationmembers_org_id_fkey'), 'organizationmembers', 'organizations', ['org_id'], ['id'])
    op.drop_constraint(None, 'organizationmembers', type_='unique')
    op.alter_column('organizationmembers', 'joined_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'milestones', type_='foreignkey')
    op.drop_constraint(None, 'milestones', type_='foreignkey')
    op.drop_constraint(None, 'milestones', type_='foreignkey')
    op.create_foreign_key(op.f('milestones_proj_id_fkey'), 'milestones', 'projects', ['proj_id'], ['id'])
    op.create_foreign_key(op.f('milestones_team_id_fkey'), 'milestones', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(op.f('milestones_org_id_fkey'), 'milestones', 'organizations', ['org_id'], ['id'])
    op.drop_constraint(None, 'milestones', type_='unique')
    op.drop_constraint(None, 'labels', type_='foreignkey')
    op.drop_constraint(None, 'labels', type_='foreignkey')
    op.drop_constraint(None, 'labels', type_='foreignkey')
    op.create_foreign_key(op.f('labels_proj_id_fkey'), 'labels', 'projects', ['proj_id'], ['id'])
    op.create_foreign_key(op.f('labels_org_id_fkey'), 'labels', 'organizations', ['org_id'], ['id'])
    op.create_foreign_key(op.f('labels_team_id_fkey'), 'labels', 'teams', ['team_id'], ['id'])
    op.drop_constraint(None, 'labels', type_='unique')
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.create_foreign_key(op.f('activities_user_id_fkey'), 'activities', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('activities_org_id_fkey'), 'activities', 'organizations', ['org_id'], ['id'])
    op.drop_constraint(None, 'activities', type_='unique')
    # ### end Alembic commands ###
