"""add 'TimeStamp' to model class

Revision ID: 47f771dd55b4
Revises: 325abc5ad560
Create Date: 2026-06-25 00:13:15.567846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47f771dd55b4'
down_revision: Union[str, Sequence[str], None] = '325abc5ad560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizationmembers', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.add_column('organizationmembers', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.add_column('teammembers', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.add_column('teammembers', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teammembers', 'updated_at')
    op.drop_column('teammembers', 'created_at')
    op.drop_column('organizationmembers', 'updated_at')
    op.drop_column('organizationmembers', 'created_at')
    # ### end Alembic commands ###
